#pragma once

#define PITCHPANIC_PLUGIN_NAME "Pitch Panic"
#define PITCHPANIC_VENDOR "Panic Mechanics"
#define PITCHPANIC_URL "https://github.com/LordVinzz/PitchPanic"
#define PITCHPANIC_EMAIL ""

#define PITCHPANIC_VERSION_MAJOR 1
#define PITCHPANIC_VERSION_MINOR 0
#define PITCHPANIC_VERSION_PATCH 0

#define PITCHPANIC_STRINGIFY_IMPL(x) #x
#define PITCHPANIC_STRINGIFY(x) PITCHPANIC_STRINGIFY_IMPL(x)
#define PITCHPANIC_VERSION_STRING \
    PITCHPANIC_STRINGIFY(PITCHPANIC_VERSION_MAJOR) "." \
    PITCHPANIC_STRINGIFY(PITCHPANIC_VERSION_MINOR) "." \
    PITCHPANIC_STRINGIFY(PITCHPANIC_VERSION_PATCH)
